# Generated by Django 3.1.3 on 2021-02-04 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0037_auto_20210204_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRelationAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playCount', models.IntegerField()),
                ('uniquePlayCount', models.IntegerField()),
                ('playTime', models.IntegerField()),
                ('uniquePlayTime', models.IntegerField()),
                ('viewCount', models.IntegerField()),
                ('viewTime', models.IntegerField()),
                ('storyViewTime', models.IntegerField()),
                ('storyUniqueViewTime', models.IntegerField()),
                ('videoRelation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.videorelation')),
            ],
            options={
                'db_table': 'VideoRelationAnalysis',
            },
        ),
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playCount', models.IntegerField()),
                ('swichingCount', models.IntegerField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
            options={
                'db_table': 'VideoAnalysis',
            },
        ),
        migrations.CreateModel(
            name='TagAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clickCount', models.IntegerField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.linktag')),
            ],
            options={
                'db_table': 'TagAnalysis',
            },
        ),
        migrations.CreateModel(
            name='PopupTagAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clickCount', models.IntegerField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.linktag')),
            ],
            options={
                'db_table': 'PopupTagAnalysis',
            },
        ),
    ]
