# Generated by Django 3.1.3 on 2021-02-05 01:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0038_auto_20210205_1051'),
        ('view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='deleted date')),
                ('actionType', models.CharField(max_length=10)),
                ('actionTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('storyPlayTime', models.DateField()),
                ('popupBtnCount', models.IntegerField()),
                ('switchVideoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video')),
                ('tagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.linktag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='deleted date')),
                ('userAgent', models.CharField(max_length=100)),
                ('userCookie', models.CharField(max_length=100)),
                ('accessTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('leaveTime', models.DateTimeField()),
                ('playVideoRelationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.videorelation')),
            ],
            options={
                'db_table': 'UserAnalysis',
            },
        ),
        migrations.RemoveField(
            model_name='taganalysis',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='videoanalysis',
            name='video',
        ),
        migrations.RemoveField(
            model_name='videorelationanalysis',
            name='videoRelation',
        ),
        migrations.DeleteModel(
            name='PopupTagAnalysis',
        ),
        migrations.DeleteModel(
            name='TagAnalysis',
        ),
        migrations.DeleteModel(
            name='VideoAnalysis',
        ),
        migrations.DeleteModel(
            name='VideoRelationAnalysis',
        ),
        migrations.AddField(
            model_name='actionanalysis',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='view.useranalysis'),
        ),
    ]
