# Generated by Django 3.1.3 on 2021-02-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0004_auto_20210205_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionanalysis',
            old_name='actionTime',
            new_name='action_time',
        ),
        migrations.RenameField(
            model_name='actionanalysis',
            old_name='actionType',
            new_name='action_type',
        ),
        migrations.RenameField(
            model_name='actionanalysis',
            old_name='switchVideoId',
            new_name='switch_video_id',
        ),
        migrations.RenameField(
            model_name='actionanalysis',
            old_name='tagId',
            new_name='tag_id',
        ),
        migrations.RenameField(
            model_name='actionanalysis',
            old_name='userId',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='useranalysis',
            old_name='accessTime',
            new_name='access_time',
        ),
        migrations.RenameField(
            model_name='useranalysis',
            old_name='playVideoRelationId',
            new_name='play_video_relation_id',
        ),
        migrations.RenameField(
            model_name='useranalysis',
            old_name='userAgent',
            new_name='user_agent',
        ),
        migrations.RenameField(
            model_name='useranalysis',
            old_name='userCookie',
            new_name='user_cookie',
        ),
        migrations.RemoveField(
            model_name='actionanalysis',
            name='popupBtnCount',
        ),
        migrations.RemoveField(
            model_name='actionanalysis',
            name='storyPlayTime',
        ),
        migrations.RemoveField(
            model_name='useranalysis',
            name='leaveTime',
        ),
        migrations.AddField(
            model_name='actionanalysis',
            name='popup_btn_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='actionanalysis',
            name='story_play_time',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='useranalysis',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='useranalysis',
            name='leave_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='useranalysis',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
