# Generated by Django 3.1.3 on 2021-02-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0005_auto_20210205_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranalysis',
            name='user_agent',
            field=models.CharField(max_length=200),
        ),
    ]
