# Generated by Django 3.1.3 on 2021-02-05 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0006_auto_20210205_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranalysis',
            old_name='play_video_relation_id',
            new_name='video_relation_id',
        ),
    ]
