# Generated by Django 3.1.3 on 2021-02-05 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0007_auto_20210205_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionanalysis',
            old_name='popup_btn_count',
            new_name='popup_btn_flg',
        ),
        migrations.RenameField(
            model_name='actionanalysis',
            old_name='switch_video_id',
            new_name='switch_video',
        ),
        migrations.RenameField(
            model_name='actionanalysis',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='actionanalysis',
            old_name='user_id',
            new_name='user_analysis',
        ),
        migrations.RenameField(
            model_name='useranalysis',
            old_name='video_relation_id',
            new_name='video_relation',
        ),
    ]
