# Generated by Django 3.1.3 on 2021-02-08 06:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0040_auto_20210205_1106'),
        ('view', '0008_auto_20210205_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionanalysis',
            name='action_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='actionanalysis',
            name='popup_btn_flg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionanalysis',
            name='story_play_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionanalysis',
            name='switch_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.video'),
        ),
        migrations.AlterField(
            model_name='actionanalysis',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video.linktag'),
        ),
    ]
