# Generated by Django 3.1.3 on 2021-02-08 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0009_auto_20210208_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionanalysis',
            name='action_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
