# Generated by Django 3.1.3 on 2021-02-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0010_auto_20210208_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionanalysis',
            name='popup_btn_flg',
            field=models.BooleanField(default=False),
        ),
    ]
