# Generated by Django 3.1.3 on 2021-02-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0011_auto_20210208_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionanalysis',
            name='story_play_time',
        ),
        migrations.AddField(
            model_name='actionanalysis',
            name='story_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionanalysis',
            name='action_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useranalysis',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useranalysis',
            name='leave_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useranalysis',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
