# Generated by Django 3.1.3 on 2020-11-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='video_id',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='project_id',
            new_name='project',
        ),
    ]
