# Generated by Django 3.1.3 on 2020-11-19 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20201119_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='name',
            new_name='title',
        ),
    ]
