# Generated by Django 3.1.3 on 2020-11-19 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20201119_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='project',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
