# Generated by Django 3.1.3 on 2020-12-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20201202_1115'),
        ('project', '0007_auto_20201119_1910'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.AlterModelTable(
            name='project',
            table='Project',
        ),
    ]
