# Generated by Django 3.1.3 on 2021-02-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20201202_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='deleted date'),
        ),
    ]
