# Generated by Django 3.1.3 on 2021-02-05 02:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20210205_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='project',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
