# Generated by Django 3.1.3 on 2021-02-05 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20210205_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
