# Generated by Django 3.1.3 on 2020-12-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20201130_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='display_frame',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tags',
            name='hide_frame',
            field=models.IntegerField(default=1),
        ),
    ]
