# Generated by Django 3.1.3 on 2020-12-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20201202_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='display_frame',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tags',
            name='hide_frame',
            field=models.IntegerField(),
        ),
    ]
