# Generated by Django 3.1.3 on 2020-12-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20201202_1849'),
        ('video', '0006_auto_20201202_1115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='LinkTag',
        ),
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
        migrations.AlterModelTable(
            name='linktag',
            table='LinkTag',
        ),
        migrations.AlterModelTable(
            name='video',
            table='Video',
        ),
    ]
