# Generated by Django 3.1.3 on 2020-12-03 08:56

from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_endtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(null=True, upload_to=video.models.get_upload_to),
        ),
    ]
