# Generated by Django 3.1.3 on 2020-12-03 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_video_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
    ]
