# Generated by Django 3.1.3 on 2020-12-16 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_auto_20201216_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linktag',
            name='story_next_video',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='story_next_video', to='video.video'),
        ),
    ]
