# Generated by Django 3.1.3 on 2020-12-17 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0020_auto_20201217_1120'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='video',
            unique_together=set(),
        ),
    ]
