# Generated by Django 3.1.3 on 2020-12-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0021_auto_20201217_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='linktag',
            name='popup_content',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='linktag',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
