# Generated by Django 3.1.3 on 2020-12-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0022_auto_20201218_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linktag',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='linktag',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='linktag',
            name='x_coordinate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='linktag',
            name='y_coordinate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
