# Generated by Django 3.1.3 on 2021-01-05 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20201202_1849'),
        ('video', '0023_auto_20201224_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='project',
        ),
        migrations.CreateModel(
            name='VideoRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'db_table': 'VideoRelation',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='video_relation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='video.videorelation'),
            preserve_default=False,
        ),
    ]
