# Generated by Django 3.1.3 on 2021-01-08 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0025_auto_20210105_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linktag',
            name='popup_content',
        ),
        migrations.AddField(
            model_name='linktag',
            name='popup_height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linktag',
            name='popup_width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linktag',
            name='popup_x_coordinate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linktag',
            name='popup_y_coordinate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PopupText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('x_coordinate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('y_coordinate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('link_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.linktag')),
            ],
        ),
        migrations.CreateModel(
            name='PopupImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('y_coordinate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('link_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.linktag')),
            ],
            options={
                'db_table': 'PopupImg',
            },
        ),
    ]
