# Generated by Django 3.1.3 on 2021-01-08 07:10

from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0026_auto_20210108_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupimg',
            name='image',
            field=models.FileField(null=True, upload_to=video.models.get_popup_upload_to),
        ),
    ]
