# Generated by Django 3.1.3 on 2021-01-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0027_popupimg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linktag',
            name='popup_height',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='linktag',
            name='popup_width',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='linktag',
            name='popup_x_coordinate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='linktag',
            name='popup_y_coordinate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
