# Generated by Django 3.1.3 on 2021-01-12 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0028_auto_20210108_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popupimg',
            name='height',
        ),
        migrations.RemoveField(
            model_name='popuptext',
            name='height',
        ),
    ]
