# Generated by Django 3.1.3 on 2021-01-13 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0029_auto_20210112_1738'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='popuptext',
            table='PopupText',
        ),
    ]
