# Generated by Django 3.1.3 on 2021-01-20 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0032_auto_20210113_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popuptext',
            name='width',
        ),
    ]
