# Generated by Django 3.1.3 on 2021-01-25 01:43

from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0033_remove_popuptext_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popuptext',
            name='link_tag',
        ),
        migrations.AddField(
            model_name='linktag',
            name='popup_image',
            field=models.FileField(null=True, upload_to=video.models.get_popup_upload_to),
        ),
        migrations.AddField(
            model_name='linktag',
            name='popup_text',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='linktag',
            name='popup_type',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='PopupImg',
        ),
        migrations.DeleteModel(
            name='PopupText',
        ),
    ]
