# Generated by Django 3.1.3 on 2021-01-25 08:28

from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0035_auto_20210125_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linktag',
            name='popup_img',
            field=models.FileField(blank=True, null=True, upload_to=video.models.get_popup_upload_to),
        ),
    ]
