# Generated by Django 3.1.3 on 2021-02-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0036_auto_20210125_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='linktag',
            name='popup_btn_text',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='linktag',
            name='popup_btn_url',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
