# Generated by Django 3.1.3 on 2021-02-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0037_auto_20210204_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linktag',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='endtag',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='deleted date'),
        ),
        migrations.AddField(
            model_name='linktag',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='deleted date'),
        ),
        migrations.AddField(
            model_name='video',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='deleted date'),
        ),
        migrations.AddField(
            model_name='videorelation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='deleted date'),
        ),
        migrations.AlterField(
            model_name='linktag',
            name='popup_btn_url',
            field=models.URLField(blank=True, default='', max_length=100, null=True),
        ),
    ]
