# Generated by Django 3.1.3 on 2021-02-05 02:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0038_auto_20210205_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endtag',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='linktag',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='linktag',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='video',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='video',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='videorelation',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='linktag',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='video',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
