# Generated by Django 3.1.3 on 2021-02-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0040_auto_20210205_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorelation',
            name='three_dimensional_flg',
            field=models.BooleanField(default=False),
        ),
    ]
