# Generated by Django 3.1.3 on 2021-03-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0044_auto_20210303_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linktag',
            name='z_coordinate',
        ),
        migrations.AlterField(
            model_name='linktag',
            name='x_coordinate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='linktag',
            name='y_coordinate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
